#name: run main.py
#
#on:
#  schedule:
#    - cron: '0 0 * * *' # runs daily
#
#  # allows to manually run the job at any time
#  workflow_dispatch:
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    timeout-minutes: 6
#    steps:
#
#      - name: checkout repo content
#        uses: actions/checkout@v4 # checkout the repository content to GitHub runner
#
#      - name: setup python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.12' # install the python version needed
#
#      - name: install python packages
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#
#      - name: execute py script # run main.py
#        env:
#          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
#        run: python main.py
#
#      - name: commit and push files
#        run: |
#          git config --local user.email "action@github.com"
#          git config --local user.name "GitHub Action"
#          git add -A
#          git diff-index --quiet HEAD || (git commit -a -m "stats updated" --allow-empty)
#          git push
